version: "3"
services:
    mysql:
        build: ./db
        image: sandbox_mysql
        container_name: mysql_ctr
        volumes:
            - ./share:/var/share/
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo" 
        ports:
            - 3306:3306
    ruby:
        image: ruby:2.5.3
        container_name: ruby_ctr
        volumes:
            - ./gomibako:/gomibako
        environment:
            TZ: "Asia/Tokyo"
        tty: true
        stdin_open: true