version: "3"
services:
    mysql:
        build: ./db
        image: myblog_mysql
        container_name: mysql_ctr
        volumes:
            - ./share:/var/share/
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo" 
        ports:
            - 3306:3306